export const audiencePages = {
  freelancers: {
    eyebrow: 'Qlynk for freelancers and consultants',
    title: 'Let clients understand your work before the first call',
    description: 'Turn your services, process, experience, and common answers into a focused AI agent you can share with one link.',
    questions: ['What do you actually help with?', 'How does your process work?', 'Is this a fit for my project?', 'Where can I see relevant work?'],
    outcomes: [
      ['Explain your services', 'Give prospective clients consistent answers about your offer, approach, and working process.'],
      ['Surface the right proof', 'Add approved projects, examples, links, and FAQs so visitors can explore what matters to them.'],
      ['Hand off qualified interest', 'Direct visitors to your preferred contact or booking link when a real conversation is needed.'],
    ],
    ctaTitle: 'Spend less time repeating the basics.',
    ctaText: 'Give each prospect a clear place to understand your work, while you stay in control of the information and next steps.',
  },
  founders: {
    eyebrow: 'Qlynk for founders',
    title: 'Give people a clear first answer about what you are building',
    description: 'Create a focused agent for your company, product, or founder context—without turning every question into another meeting.',
    questions: ['What problem does the product solve?', 'Who is it for?', 'How does it work?', 'What should I do next?'],
    outcomes: [
      ['Keep the story consistent', 'Use approved company, product, founder, and FAQ information as the basis for every answer.'],
      ['Support different audiences', 'Help customers, partners, candidates, or media contacts find the context relevant to them.'],
      ['See what is unclear', 'Review conversations and knowledge gaps to learn which questions your existing material does not answer.'],
    ],
    ctaTitle: 'Make your company easier to understand.',
    ctaText: 'Publish the answers you are comfortable sharing, set clear boundaries, and improve the agent as new questions appear.',
  },
  creators: {
    eyebrow: 'Qlynk for creators',
    title: 'Help your audience find the right answer, resource, or next step',
    description: 'Organize your public knowledge, content, recommendations, and FAQs into an AI agent people can ask directly.',
    questions: ['Where should I start?', 'Which resource covers this?', 'How can I work with you?', 'What do you recommend for my situation?'],
    outcomes: [
      ['Guide people through your work', 'Connect questions to the videos, articles, products, or resources you have approved.'],
      ['Answer recurring audience questions', 'Keep FAQs and key context available without pretending the agent is literally you.'],
      ['Learn what people need next', 'Use conversation themes and unanswered questions to inform future content.'],
    ],
    ctaTitle: 'Make your existing work easier to explore.',
    ctaText: 'Give your audience a conversational way to navigate what you have already created and shared.',
  },
  'job-seekers': {
    eyebrow: 'Qlynk for job seekers',
    title: 'Give recruiters more context than a resume can hold',
    description: 'Create a personal AI agent that explains the experience, projects, and working context you choose to share.',
    questions: ['What did you contribute to this project?', 'Which experience is most relevant?', 'How do you approach this kind of work?', 'Where can I see an example?'],
    outcomes: [
      ['Add context to your experience', 'Explain projects, responsibilities, skills, and outcomes beyond short resume bullet points.'],
      ['Keep answers grounded', 'Choose the facts, examples, documents, and links the agent may use when responding.'],
      ['Make contact easy', 'Point interested recruiters or hiring managers to your preferred next step.'],
    ],
    ctaTitle: 'Let your work speak beyond the page.',
    ctaText: 'Share a focused, clearly identified AI representative alongside your resume, portfolio, or professional profile.',
  },
  business: {
    eyebrow: 'Qlynk for businesses',
    title: 'Answer routine customer questions without pulling someone away',
    description: 'Turn your services, policies, product details, procedures, and FAQs into a focused business agent people can use through one link.',
    questions: ['Do you offer what I need?', 'What is included?', 'How does the process work?', 'Who should I contact?'],
    outcomes: [
      ['Make key information easier to find', 'Give customers one conversational place for approved service, product, policy, and process information.'],
      ['Set useful boundaries', 'Define the agent’s audience, allowed topics, blocked topics, uncertainty response, and escalation path.'],
      ['Improve from real questions', 'Review conversation themes and knowledge gaps to see where customers still need clarity.'],
    ],
    ctaTitle: 'Give customers a faster way to understand your business.',
    ctaText: 'Start with the questions your team answers every day, then add more approved knowledge as you learn what people need.',
  },
};
