const solution = ({ slug, cluster, title, description, what, audience, benefits, steps, question, answer, faqs, related, keywords }) => ({
  slug,
  cluster,
  title,
  shortTitle: title.replace(/\s*\|.*$/, ''),
  description,
  what,
  audience,
  benefits,
  steps,
  example: { question, answer },
  faqs,
  related,
  keywords,
});

export const solutionClusters = [
  { key: 'core', name: 'Core AI agent platform', description: 'Build, govern, publish, and improve a trusted AI agent from knowledge you approve.' },
  { key: 'people', name: 'People & experts', description: 'Make professional knowledge easier for clients, audiences, and employers to explore.' },
  { key: 'business', name: 'Business', description: 'Answer recurring customer, sales, product, and documentation questions.' },
  { key: 'operations', name: 'Operations', description: 'Turn reviewed procedures into guided answers for employees and support teams.' },
  { key: 'places', name: 'Properties & places', description: 'Give guests, residents, and visitors a focused guide they can open from one link.' },
];

export const solutionPages = {
  'ai-agent-builder': solution({
    slug: 'ai-agent-builder', cluster: 'core', title: 'AI Agent Builder for Approved Knowledge',
    description: 'Build a focused AI agent from facts, FAQs, links, and documents you review—then publish it through a simple link or website widget.',
    what: 'Qlynk is a no-code AI agent builder for turning maintained knowledge into a conversational guide with a defined purpose, audience, topic scope, tone, and human handoff.',
    audience: 'Professionals and small teams that repeatedly explain the same information and want a controlled, shareable first line of help.',
    benefits: [['Start with a job', 'Choose a person, business, property, operation, product, support, or custom-guide role instead of an open-ended bot.'], ['Keep answers maintainable', 'Add reviewed facts, FAQs, links, notes, and supported documents, then update them when the source changes.'], ['Publish without development', 'Share a hosted Qlynk page or add the agent to a website with an embed.']],
    steps: [['Define', 'Describe the agent’s purpose, audience, useful topics, blocked topics, and escalation path.'], ['Teach', 'Add only the source material the agent needs for that job and review it before publishing.'], ['Test and share', 'Try expected, uncertain, and out-of-scope questions, then publish the link when the behavior is ready.']],
    question: 'Can this agent answer questions outside our approved service guide?', answer: 'I’ll stay within the service information this team has provided. For anything outside that scope, I can point you to the right person.',
    faqs: [['Do I need to code?', 'No. Qlynk provides guided setup, a hosted page, and an embeddable widget.'], ['What knowledge can I add?', 'You can add profile context, capabilities, projects, facts, FAQs, links, custom notes, and supported documents.'], ['Can I control the agent’s scope?', 'Yes. You can define its purpose, audience, allowed and blocked topics, behavior rules, uncertainty handling, and handoff.']],
    related: ['custom-ai-agents', 'knowledge-based-ai', 'ai-knowledge-platform'], keywords: ['AI agent builder', 'AI assistant builder', 'no-code AI agent'],
  }),
  'custom-ai-agents': solution({
    slug: 'custom-ai-agents', cluster: 'core', title: 'Custom AI Agents With a Defined Job',
    description: 'Create a custom AI agent around your audience, approved knowledge, voice, boundaries, and next step—not a generic chatbot.',
    what: 'A custom Qlynk Agent combines an owner-defined job with a curated knowledge base and a visitor experience you can name, style, test, and share.',
    audience: 'Anyone whose use case does not fit a generic support template or who needs the agent to follow specific communication rules.',
    benefits: [['Fit the real use case', 'Set the purpose and audience before adding content.'], ['Make boundaries visible', 'Configure topics to cover, topics to avoid, uncertainty behavior, and escalation.'], ['Create a recognizable experience', 'Choose the identity, welcome message, suggested questions, tone, response length, and colors.']],
    steps: [['Choose Custom Guide', 'Start with the custom agent type and describe the outcome it should help visitors reach.'], ['Configure knowledge and rules', 'Add the approved material and write explicit do, don’t, and handoff guidance.'], ['Review as a visitor', 'Test the public experience, refine weak answers, and share the Qlynk link.']],
    question: 'Can you help me decide whether this project is eligible?', answer: 'I can explain the published eligibility criteria and the application steps. A team member must confirm any final eligibility decision.',
    faqs: [['What makes the agent custom?', 'Its job, audience, knowledge, boundaries, identity, suggested questions, response style, and public presentation are configurable.'], ['Can it make decisions for my organization?', 'It should explain approved criteria and route decisions that require judgment or authorization to a person.'], ['Can I update it later?', 'Yes. You can revise the configuration and knowledge without training a new foundation model.']],
    related: ['ai-agent-builder', 'knowledge-based-ai', 'business-ai-assistant'], keywords: ['custom AI agent', 'build custom AI agents', 'custom AI assistant'],
  }),
  'knowledge-based-ai': solution({
    slug: 'knowledge-based-ai', cluster: 'core', title: 'Knowledge-Based AI Grounded in Your Sources',
    description: 'Give people a conversational way to use the information you have reviewed, with clear scope and uncertainty rules.',
    what: 'Knowledge-based AI retrieves relevant material from a maintained source set and uses it as context for an answer. Qlynk adds agent purpose, boundaries, publishing, and review around that process.',
    audience: 'Teams and experts with reliable reference material that is hard for visitors or employees to navigate quickly.',
    benefits: [['Ground answers in maintained material', 'Use approved facts, FAQs, notes, links, and documents as the working knowledge.'], ['Reduce unsupported improvisation', 'Tell the agent what belongs in scope and how to respond when the answer is absent.'], ['Improve from real gaps', 'Review conversations and unanswered topics to decide what knowledge deserves to be added.']],
    steps: [['Curate', 'Choose the smallest source set that fully supports the agent’s job.'], ['Structure', 'Turn critical details into clear facts and FAQs instead of relying only on long documents.'], ['Maintain', 'Test answers and update the source when policy, availability, or instructions change.']],
    question: 'What is your refund window?', answer: 'The approved policy says refund requests must be submitted within 14 days of purchase. I can show you the request steps, but a team member confirms the outcome.',
    faqs: [['Does knowledge grounding eliminate hallucinations?', 'No system can promise that. Good sources, narrow scope, explicit uncertainty behavior, testing, and human escalation reduce the risk.'], ['Is this the same as model retraining?', 'No. You update the knowledge supplied to the agent; you do not need to retrain a foundation model.'], ['What should stay out of the knowledge base?', 'Keep out passwords, access codes, private customer data, confidential records, and material you are not permitted to use.']],
    related: ['ai-knowledge-platform', 'ai-documentation-assistant', 'ai-hallucinations-approved-knowledge'], keywords: ['knowledge-based AI', 'knowledge AI', 'AI knowledge base'],
  }),
  'ai-knowledge-platform': solution({
    slug: 'ai-knowledge-platform', cluster: 'core', title: 'AI Knowledge Platform for Shareable Answers',
    description: 'Organize approved information, define how an agent should use it, and make it available through a public page or embedded chat.',
    what: 'Qlynk is an AI knowledge platform that joins content, behavioral controls, a conversational interface, and a feedback loop in one owner-managed agent.',
    audience: 'Small organizations that need a practical publishing layer for knowledge without building a search or chat application themselves.',
    benefits: [['One working source set', 'Bring together structured answers and supporting documents for a single agent.'], ['Rules travel with the knowledge', 'Purpose, tone, limits, and escalation are configured alongside the source material.'], ['A usable destination', 'People access the knowledge through suggested questions, conversational search, and a branded interface.']],
    steps: [['Map the audience’s questions', 'List the recurring questions and the approved source for each answer.'], ['Build the knowledge set', 'Add concise facts and FAQs first, then attach documents and links where they add context.'], ['Publish and govern', 'Test, share, review gaps, and assign responsibility for updates.']],
    question: 'Where is the latest onboarding checklist?', answer: 'The approved onboarding guide places the checklist in the “First Week” section. I can summarize the steps here and link you to the maintained source.',
    faqs: [['Is Qlynk a document storage system?', 'It is an agent and knowledge experience, not a replacement for your authoritative document repository.'], ['Who should maintain the knowledge?', 'A named owner who understands the subject and can confirm when information changes.'], ['Can the same agent serve every department?', 'A narrower agent is usually easier to govern. Use one clearly defined job and audience rather than combining unrelated knowledge.']],
    related: ['knowledge-based-ai', 'ai-agent-builder', 'ai-knowledge-management'], keywords: ['AI knowledge platform', 'AI knowledge management platform', 'RAG AI platform'],
  }),

  'ai-for-consultants': solution({
    slug: 'ai-for-consultants', cluster: 'people', title: 'AI for Consultants Who Repeat the Same Explanations',
    description: 'Help prospects understand your expertise, engagement process, fit, and next steps from knowledge you approve.',
    what: 'A consultant AI agent is a focused public guide to your services, methods, experience, frequently asked questions, and contact path.', audience: 'Independent consultants and advisory firms that want to qualify interest and explain their work before a discovery call.',
    benefits: [['Explain your offer consistently', 'Give prospects the same reviewed description of scope, approach, and deliverables.'], ['Set expectations early', 'Clarify fit, timelines, preparation, and what requires a conversation.'], ['Make expertise explorable', 'Let visitors ask questions in their own words rather than search a long services page.']],
    steps: [['Choose the recurring questions', 'Start with fit, process, deliverables, and the problems you are equipped to solve.'], ['Add approved examples', 'Include public case context without exposing client-confidential information.'], ['Handoff at the right moment', 'Invite a discovery call when the question depends on the prospect’s circumstances.']],
    question: 'Would you be a fit for a two-week compliance review?', answer: 'I can explain the published engagement types and preparation requirements. Scope and availability depend on your situation, so the next step is a short discovery call.',
    faqs: [['Will the agent give consulting advice?', 'It should explain your published knowledge and services, not replace professional judgment or make client-specific recommendations without review.'], ['Can I include case studies?', 'Yes, if they are approved for public use and do not disclose confidential details.'], ['Can prospects contact me from the agent?', 'You can define a human handoff and provide the appropriate contact or booking link.']],
    related: ['ai-for-coaches', 'personal-ai-assistant', 'ai-sales-assistant'], keywords: ['AI for consultants', 'consultant AI assistant', 'consulting AI agent'],
  }),
  'ai-for-coaches': solution({
    slug: 'ai-for-coaches', cluster: 'people', title: 'AI for Coaches and Their Prospective Clients',
    description: 'Explain your coaching focus, format, expectations, and resources without turning an AI agent into a substitute for coaching.',
    what: 'A coach AI agent answers practical questions about your program and shares approved educational material while keeping personal guidance and sensitive conversations with the coach.', audience: 'Coaches who want a clear, always-available introduction to their approach and program logistics.',
    benefits: [['Clarify the program', 'Explain who it is for, meeting format, preparation, and common next steps.'], ['Protect the boundary', 'State that the agent is informational and route personal, medical, legal, or high-stakes questions to a person.'], ['Support between touchpoints', 'Make approved exercises and public resources easier to find.']],
    steps: [['Define informational scope', 'Separate program information from advice that requires a coaching relationship.'], ['Add program knowledge', 'Publish reviewed FAQs, formats, resources, and expectations.'], ['Test sensitive questions', 'Confirm the agent declines or hands off situations that need human care.']],
    question: 'What should I do about a serious issue at work?', answer: 'I can share the coach’s general public framework, but I can’t assess your personal situation. Please contact the coach directly or seek an appropriate qualified professional.',
    faqs: [['Can it coach clients automatically?', 'Qlynk is best used to explain approved material and logistics; it should not replace a coach’s judgment or relationship.'], ['Can it share exercises?', 'Yes, when those exercises are approved for the audience and accompanied by appropriate context.'], ['Can I block sensitive topics?', 'You can specify blocked topics, behavioral rules, uncertainty handling, and escalation guidance.']],
    related: ['ai-for-consultants', 'personal-ai-assistant', 'ai-for-speakers'], keywords: ['AI for coaches', 'coach AI assistant', 'coaching AI agent'],
  }),
  'personal-ai-assistant': solution({
    slug: 'personal-ai-assistant', cluster: 'people', title: 'Personal AI Assistant for Your Public Knowledge',
    description: 'Create a shareable AI representative for your work, experience, projects, services, and public answers.',
    what: 'A Qlynk personal AI assistant helps other people explore information you choose to publish. It is a focused representative, not an impersonator or a general assistant acting with your authority.', audience: 'Professionals, creators, advisors, candidates, and public experts with recurring questions about their work.',
    benefits: [['Available through one link', 'Add the agent to a profile, email, portfolio, or QR code.'], ['Represent the work clearly', 'Use a chosen identity, welcome message, suggested questions, and tone.'], ['Keep authority with the owner', 'The agent explains approved information and directs decisions or private matters back to you.']],
    steps: [['Choose the public job', 'Decide whether the agent explains a portfolio, services, expertise, talks, or career experience.'], ['Select public knowledge', 'Add only information you are comfortable making accessible to visitors.'], ['Test for impersonation risk', 'Ensure it identifies itself as AI and does not claim personal actions, opinions, or commitments you did not provide.']],
    question: 'Would Zeyad accept this project next month?', answer: 'I can explain Zeyad’s published project criteria, but I cannot confirm availability or make a commitment. Please use the contact link for a direct answer.',
    faqs: [['Is this a digital clone of me?', 'It is a focused AI representative built from information you choose, not a copy of your identity or judgment.'], ['Is my entire account public?', 'Visitors see the published agent experience, not your private dashboard. You choose what knowledge to add and should exclude sensitive data.'], ['Can I change its voice and appearance?', 'Yes. Identity, welcome copy, suggested questions, tone, response length, colors, and supported visual settings are configurable.']],
    related: ['ai-portfolio-assistant', 'ai-resume-assistant', 'ai-for-speakers'], keywords: ['personal AI assistant', 'personal AI agent', 'AI assistant for professionals'],
  }),
  'ai-portfolio-assistant': solution({
    slug: 'ai-portfolio-assistant', cluster: 'people', title: 'AI Portfolio Assistant That Explains the Work',
    description: 'Turn projects, capabilities, decisions, and outcomes you can substantiate into an interactive portfolio guide.',
    what: 'An AI portfolio assistant helps visitors navigate approved project information and understand what you contributed, how you approached the work, and where to learn more.', audience: 'Designers, developers, freelancers, studios, and specialists whose work needs more context than thumbnails provide.',
    benefits: [['Add context to projects', 'Explain roles, constraints, methods, and published results behind each example.'], ['Guide different visitors', 'Let recruiters, clients, and collaborators ask the questions relevant to them.'], ['Keep claims reviewable', 'Base answers on portfolio facts you maintain instead of letting the agent invent a narrative.']],
    steps: [['Structure each project', 'Record the problem, your role, process, deliverable, and only outcomes you can verify.'], ['Add capabilities and links', 'Connect project examples to the skills or services they demonstrate.'], ['Test attribution questions', 'Check that the agent distinguishes your contribution from the wider team’s work.']],
    question: 'Did you design and build this entire product?', answer: 'The project record says the owner led the interface design and frontend implementation. Strategy and backend work were handled by the wider team.',
    faqs: [['Can it replace my portfolio website?', 'It can be the public experience or complement an existing portfolio through a link or widget.'], ['Should I include client results?', 'Only include outcomes you can substantiate and are permitted to publish.'], ['Can it direct people to a project page?', 'Yes. Add approved links and tell the agent when they should be suggested.']],
    related: ['personal-ai-assistant', 'ai-resume-assistant', 'ai-for-consultants'], keywords: ['AI portfolio assistant', 'interactive AI portfolio', 'portfolio AI agent'],
  }),
  'ai-for-speakers': solution({
    slug: 'ai-for-speakers', cluster: 'people', title: 'AI for Speakers, Hosts, and Event Organizers',
    description: 'Give organizers and audience members a trusted guide to your talks, topics, biography, resources, and booking process.',
    what: 'A speaker AI agent answers recurring public questions before and after an event from an approved speaker kit and resource library.', audience: 'Speakers, educators, conference hosts, and subject-matter experts who serve organizers and audiences.',
    benefits: [['Help organizers evaluate fit', 'Explain talk topics, intended audiences, formats, and published requirements.'], ['Extend the session', 'Point attendees to approved references, reading, and answers after the talk.'], ['Protect booking decisions', 'Route fees, dates, contracts, and custom commitments to the speaker or representative.']],
    steps: [['Build the speaker kit', 'Add biography, talk descriptions, audience fit, format, media, and public resources.'], ['Separate public and negotiable details', 'Keep contractual or changing information behind a human handoff.'], ['Share around the event', 'Use the Qlynk link in the speaker profile, slides, program, or follow-up.']],
    question: 'Can this keynote be customized for our leadership retreat?', answer: 'The speaker offers a published customization process. The agent can explain the available themes; the speaker must confirm the final brief, fee, and date.',
    faqs: [['Can the agent confirm a booking?', 'It should explain the process and route the decision to the authorized person.'], ['Can attendees use it after a talk?', 'Yes. Add approved resources and questions, then share the link in event materials.'], ['Can I change information for each event?', 'You can update the agent’s knowledge and suggested questions as your public information changes.']],
    related: ['personal-ai-assistant', 'ai-for-coaches', 'ai-visitor-guide'], keywords: ['AI for speakers', 'speaker AI assistant', 'event speaker AI'],
  }),
  'ai-resume-assistant': solution({
    slug: 'ai-resume-assistant', cluster: 'people', title: 'AI Resume Assistant for Candidate Questions',
    description: 'Let recruiters explore verified experience, skills, projects, and role preferences without adding claims beyond your record.',
    what: 'A resume AI assistant is an interactive companion to a CV or portfolio. It explains candidate-provided experience and directs requests for references, availability, or decisions to the candidate.', audience: 'Job seekers and independent professionals who want hiring teams to navigate their experience conversationally.',
    benefits: [['Make experience searchable', 'Answer questions across roles, skills, projects, and education.'], ['Add context within limits', 'Explain responsibilities and examples without embellishing titles, dates, or results.'], ['Offer a direct next step', 'Guide the recruiter to contact details, portfolio links, or the preferred interview process.']],
    steps: [['Verify the record', 'Use the current CV and approved project notes as the source of truth.'], ['Map likely recruiter questions', 'Cover role fit, relevant examples, tools, collaboration, and location or work preferences.'], ['Test claim boundaries', 'Ask leading questions and confirm that the agent does not overstate seniority, ownership, or outcomes.']],
    question: 'Did you lead the engineering department?', answer: 'The approved resume says the candidate led a three-person project team, not the full engineering department.',
    faqs: [['Will it write or change my resume?', 'This use case publishes and explains the information you approve; you remain responsible for the underlying resume.'], ['Can it answer salary or availability questions?', 'You can include current preferences, but changing or negotiable details are often better handled directly.'], ['Should references be uploaded?', 'Do not add private reference contact details without permission. The agent can explain how references are provided.']],
    related: ['ai-portfolio-assistant', 'personal-ai-assistant', 'ai-for-consultants'], keywords: ['AI resume assistant', 'interactive AI resume', 'AI CV assistant'],
  }),

  'business-ai-assistant': solution({
    slug: 'business-ai-assistant', cluster: 'business', title: 'Business AI Assistant for Approved Answers',
    description: 'Give customers and teams a focused AI guide to services, policies, processes, products, and next steps.',
    what: 'A business AI assistant answers recurring questions from company-approved knowledge while following defined limits and directing exceptions to a person.', audience: 'Small businesses and teams that need a practical first line of information without creating a broad automation program.',
    benefits: [['Reduce repeated explanations', 'Handle common questions about offers, policies, and processes.'], ['Use one reviewed message', 'Keep the answer set aligned with information the business maintains.'], ['Preserve human ownership', 'Escalate exceptions, decisions, complaints, and sensitive requests.']],
    steps: [['Pick one business job', 'Start with support, FAQs, product guidance, sales information, or internal knowledge.'], ['Approve the sources', 'Review policies, service details, documents, and links before adding them.'], ['Publish where questions happen', 'Share the Qlynk link or embed the widget, then review knowledge gaps.']],
    question: 'Can you guarantee delivery by Friday?', answer: 'The published delivery estimate is three to five business days. I cannot guarantee a date; the team can confirm availability for your order.',
    faqs: [['Is it only for customer support?', 'No. Qlynk includes business, property, operations, product, support, personal, and custom-guide agent types.'], ['Can it answer private account questions?', 'Only add and expose information appropriate for the intended audience. Qlynk’s public agent is best for approved shared knowledge, not private account records.'], ['What happens when it does not know?', 'Configure it to acknowledge uncertainty and offer the correct human handoff.']],
    related: ['ai-customer-support', 'ai-faq-assistant', 'ai-sales-assistant'], keywords: ['business AI assistant', 'AI for small business', 'enterprise AI assistant'],
  }),
  'ai-customer-support': solution({
    slug: 'ai-customer-support', cluster: 'business', title: 'AI Customer Support for the First Answer',
    description: 'Answer common support questions from reviewed material and hand off issues that require account access, judgment, or action.',
    what: 'A Qlynk support agent is a knowledge-first layer for explanations, troubleshooting steps, policies, and routing. It does not replace a help desk that must authenticate users or perform transactions.', audience: 'Businesses with repeat support questions and a maintained set of public or audience-appropriate answers.',
    benefits: [['Give immediate guidance', 'Explain common setup steps, policies, and known resolutions.'], ['Protect exception handling', 'Send billing disputes, account changes, safety issues, and unresolved cases to a person.'], ['See what is missing', 'Review conversations and knowledge gaps to improve documentation.']],
    steps: [['Prioritize frequent requests', 'Start with high-volume, low-risk questions that have stable approved answers.'], ['Write resolution and escalation rules', 'State what the agent may explain and what requires authenticated support.'], ['Monitor the handoff', 'Test that contact information and escalation language remain current.']],
    question: 'Can you cancel my subscription and refund the last payment?', answer: 'I can explain the published cancellation and refund policy, but I cannot access or change your account. Please contact billing support through the secure channel.',
    faqs: [['Does Qlynk create support tickets?', 'Qlynk currently provides a defined human handoff; do not assume ticketing or account actions unless you have separately implemented them.'], ['Can it troubleshoot a product?', 'Yes, using approved steps and clear stop conditions for situations that need a person.'], ['How should we measure usefulness?', 'Review repeated questions, weak answers, knowledge gaps, and whether visitors reach the correct next step.']],
    related: ['ai-help-desk', 'ai-faq-assistant', 'how-to-build-customer-support-ai'], keywords: ['customer support AI', 'AI customer service assistant', 'support AI agent'],
  }),
  'ai-faq-assistant': solution({
    slug: 'ai-faq-assistant', cluster: 'business', title: 'AI FAQ Assistant for Natural-Language Questions',
    description: 'Turn a reviewed FAQ into an agent that understands different phrasings, explains answers, and knows when to stop.',
    what: 'An AI FAQ assistant retrieves relevant approved answers even when visitors do not use the exact wording on the page.', audience: 'Organizations with recurring informational questions that are difficult to cover with a long accordion or menu.',
    benefits: [['Meet people in their wording', 'Let visitors ask a full question instead of guessing the right category.'], ['Keep critical answers explicit', 'Use reviewed Q&A pairs for prices, policies, instructions, and eligibility language.'], ['Reveal the next FAQ', 'Use real gaps to decide which missing answer should be documented.']],
    steps: [['Collect actual questions', 'Use support logs, sales calls, and team knowledge without importing private customer details.'], ['Write direct approved answers', 'Lead with the answer, add conditions, and link to the authoritative source.'], ['Test variants and gaps', 'Try alternate wording, compound questions, and questions the FAQ cannot answer.']],
    question: 'Do I need a credit card to try Qlynk?', answer: 'No payment is taken today for the 14-day trial. The pricing page explains the current signup and plan details.',
    faqs: [['Is an AI FAQ better than a normal FAQ page?', 'They can work together. A page is easy to scan and index; the agent helps visitors phrase questions naturally and reach the relevant answer.'], ['Can answers link to policies?', 'Yes. Add and maintain the approved link in the source material.'], ['Should every question receive an answer?', 'No. Sensitive, uncertain, account-specific, or out-of-scope questions should be handed off.']],
    related: ['ai-customer-support', 'ai-documentation-assistant', 'knowledge-based-ai'], keywords: ['AI FAQ assistant', 'FAQ chatbot', 'AI FAQ generator'],
  }),
  'ai-sales-assistant': solution({
    slug: 'ai-sales-assistant', cluster: 'business', title: 'AI Sales Assistant for Product and Service Questions',
    description: 'Help prospects understand fit, options, prerequisites, and next steps without letting an agent invent promises or negotiate.',
    what: 'A Qlynk sales assistant is a pre-sales information guide grounded in approved offer details, qualification criteria, and contact paths.', audience: 'Small sales teams, founders, consultants, and product businesses with recurring evaluation questions.',
    benefits: [['Clarify fit before a call', 'Explain intended users, use cases, inclusions, and known limitations.'], ['Keep commercial claims controlled', 'Use reviewed pricing and product language instead of generated promises.'], ['Move to a human at the decision point', 'Route negotiation, custom scope, availability, and contractual commitments.']],
    steps: [['Map the buying questions', 'Cover problem fit, options, setup, price context, proof, and next step.'], ['Approve claims and exclusions', 'Document what the offer does and does not include.'], ['Test pressure questions', 'Confirm the agent will not fabricate discounts, guarantees, roadmaps, or contract terms.']],
    question: 'Can you promise this integration will be delivered next week?', answer: 'The approved offer does not include that delivery guarantee. I can explain the standard scope, and the team can assess a custom timeline.',
    faqs: [['Can it qualify leads?', 'It can explain published fit criteria and guide visitors to the next step; it should not claim automated scoring or CRM actions that are not implemented.'], ['Can it negotiate price?', 'No. Use the agent for transparent published pricing and route negotiation to an authorized person.'], ['Can it compare packages?', 'Yes, when the package details are current and maintained in the knowledge base.']],
    related: ['ai-product-guide', 'business-ai-assistant', 'ai-for-consultants'], keywords: ['AI sales assistant', 'sales AI agent', 'AI pre-sales assistant'],
  }),
  'ai-product-guide': solution({
    slug: 'ai-product-guide', cluster: 'business', title: 'AI Product Guide for Confident Evaluation',
    description: 'Help buyers and users understand features, compatibility, setup, care, and limitations from current product knowledge.',
    what: 'An AI product guide is a conversational layer over approved specifications, usage guidance, comparison criteria, and support information.', audience: 'Product teams, retailers, SaaS companies, and makers with detailed products that generate repeated questions.',
    benefits: [['Make specifications usable', 'Answer questions in the context of what a visitor is trying to do.'], ['Keep limitations discoverable', 'Explain compatibility, exclusions, prerequisites, and safe-use guidance.'], ['Connect evaluation to help', 'Guide visitors to product pages, documentation, support, or a sales contact.']],
    steps: [['Create a product truth set', 'Use current specifications, variants, policies, setup guides, and known limitations.'], ['Add decision questions', 'Document how products differ without inventing personal recommendations.'], ['Update with releases', 'Review the knowledge whenever specifications, availability, or instructions change.']],
    question: 'Will this work with my older device?', answer: 'The compatibility guide lists versions 12 and later. I cannot confirm an unlisted device, so please share the exact model with support before purchasing.',
    faqs: [['Can it recommend a product?', 'It can explain approved differences and suitability criteria, while uncertain or high-stakes choices should go to a person.'], ['Can it use a product manual?', 'Yes. Supported documents can provide context, and critical answers should also be made clear in structured facts or FAQs.'], ['How do we prevent outdated answers?', 'Assign an owner and update the agent whenever specifications, pricing, policies, or availability change.']],
    related: ['ai-sales-assistant', 'ai-documentation-assistant', 'ai-faq-assistant'], keywords: ['AI product guide', 'product assistant AI', 'product knowledge AI'],
  }),
  'ai-documentation-assistant': solution({
    slug: 'ai-documentation-assistant', cluster: 'business', title: 'AI Documentation Assistant for Faster Answers',
    description: 'Help readers find and understand maintained documentation while preserving the source as the authority.',
    what: 'An AI documentation assistant retrieves relevant guidance from approved docs and explains it conversationally, with links and escalation for missing or version-specific details.', audience: 'Product, service, and operations teams with documentation that users struggle to search or navigate.',
    benefits: [['Reduce search friction', 'Connect a natural-language question to the relevant maintained guidance.'], ['Keep the source authoritative', 'Use the assistant as a navigation and explanation layer, not the only copy of the rule.'], ['Find documentation gaps', 'Review questions that the current docs cannot answer clearly.']],
    steps: [['Choose the authoritative set', 'Remove duplicates and identify the current source for each topic.'], ['Improve document structure', 'Use descriptive headings, explicit steps, version context, and stable links.'], ['Test retrieval questions', 'Try synonyms, error messages, multi-step tasks, and unsupported versions.']],
    question: 'How do I publish the agent after changing its rules?', answer: 'The setup guide says to save the updated configuration, test it in preview, and then use the publishing controls. If the save state is unclear, do not close the page until it confirms completion.',
    faqs: [['Does this replace documentation?', 'No. Good documentation remains the maintained source; the assistant makes it easier to use.'], ['Can it cite the source?', 'Include stable source links in the knowledge and instruct the agent to direct readers to them when appropriate.'], ['What documents work best?', 'Current, text-readable, well-structured documents with clear ownership and no conflicting versions.']],
    related: ['ai-knowledge-platform', 'ai-faq-assistant', 'ai-documentation-best-practices'], keywords: ['AI documentation', 'AI documentation assistant', 'documentation chatbot'],
  }),

  'ai-employee-training': solution({
    slug: 'ai-employee-training', cluster: 'operations', title: 'AI Employee Training From Reviewed Material',
    description: 'Make approved policies, procedures, role guidance, and learning resources easier for employees to explore.',
    what: 'An employee training AI agent answers informational questions from reviewed internal training knowledge. It complements instructors, managers, and required systems rather than certifying competence.', audience: 'Small teams with recurring training questions and a clear set of audience-appropriate resources.',
    benefits: [['Support self-directed review', 'Let employees revisit concepts and steps in their own words.'], ['Keep guidance consistent', 'Use the same reviewed policy and procedure language across common questions.'], ['Escalate judgment calls', 'Direct safety, HR, legal, customer, and approval decisions to the responsible person.']],
    steps: [['Choose one learning objective', 'Start with a role, procedure, product, or first-week training need.'], ['Add approved learning content', 'Include current steps, definitions, examples, and the owner of each policy.'], ['Test safe failure', 'Confirm the agent identifies missing context and never treats a chat as formal certification.']],
    question: 'Am I certified to perform this task now?', answer: 'I can help you review the approved procedure, but I cannot assess or certify competence. Please complete the required training and supervisor sign-off.',
    faqs: [['Can it track course completion?', 'Do not assume learning-management or certification features. Qlynk provides a knowledge and guidance experience.'], ['Can it include policies?', 'Yes, for the intended audience, with current ownership and an escalation path for interpretation.'], ['Should employees rely on it for emergencies?', 'No. Emergency and safety-critical instructions must use the organization’s official procedures and trained human channels.']],
    related: ['ai-onboarding-assistant', 'ai-sop-assistant', 'ai-operations-manual'], keywords: ['AI employee training', 'AI training assistant', 'employee learning AI'],
  }),
  'ai-sop-assistant': solution({
    slug: 'ai-sop-assistant', cluster: 'operations', title: 'AI SOP Assistant for Procedure Questions',
    description: 'Turn current standard operating procedures into guided answers while keeping the approved SOP as the authority.',
    what: 'An AI SOP assistant helps a defined audience find steps, prerequisites, stop conditions, and escalation instructions from reviewed procedures.', audience: 'Operations teams with stable procedures that are difficult to search during day-to-day work.',
    benefits: [['Find the relevant step', 'Ask about the task or situation instead of scanning an entire manual.'], ['Surface stop conditions', 'Make prerequisites, exceptions, approvals, and safety limits part of the answer.'], ['Expose unclear SOPs', 'Use weak or unanswered questions as a signal that the source procedure needs work.']],
    steps: [['Select the current SOP', 'Exclude superseded versions and record the owner and revision date.'], ['Structure the critical logic', 'Add prerequisites, ordered steps, exceptions, and escalation as clear knowledge.'], ['Test abnormal situations', 'Ask about missing inputs, failed checks, and conditions that require stopping.']],
    question: 'The inspection result is outside the normal range. Should I continue?', answer: 'No. The approved SOP says to stop, record the result, and contact the shift supervisor before continuing.',
    faqs: [['Can the agent change an SOP?', 'No. Changes belong in the controlled source and should be approved through the organization’s process.'], ['Is this suitable for safety-critical work?', 'It may help people find information, but it must not replace required training, signage, controls, or human authority.'], ['How do we handle versions?', 'Keep only the applicable material in scope and include the source version or revision date in critical guidance.']],
    related: ['ai-operations-manual', 'ai-employee-training', 'ai-onboarding-assistant'], keywords: ['AI SOP assistant', 'standard operating procedure AI', 'operations AI assistant'],
  }),
  'ai-operations-manual': solution({
    slug: 'ai-operations-manual', cluster: 'operations', title: 'AI Operations Manual People Can Ask',
    description: 'Give teams a conversational route into approved operational policies, responsibilities, checklists, and escalation paths.',
    what: 'An AI operations manual is a focused agent over maintained operational guidance, designed to answer routine questions and point people to the authoritative process.', audience: 'Businesses, properties, venues, and teams whose operational knowledge spans multiple guides and recurring questions.',
    benefits: [['Connect scattered guidance', 'Help a user reach the right approved procedure or owner.'], ['Clarify responsibility', 'Explain who performs, checks, approves, or receives each routine task.'], ['Keep exceptions human', 'Route unusual, sensitive, or high-impact decisions to the named role.']],
    steps: [['Map the manual', 'Organize the current policies, routines, roles, and escalation routes by task.'], ['Remove conflicts', 'Resolve duplicate or inconsistent instructions before the agent uses them.'], ['Maintain an update rhythm', 'Review the knowledge after process, staffing, policy, or facility changes.']],
    question: 'Who approves a purchase above the routine limit?', answer: 'The current operations guide assigns approval above the routine limit to the operations manager. I can show the request checklist.',
    faqs: [['Is this a replacement for controlled manuals?', 'No. Keep the controlled source authoritative and use Qlynk to make it easier to navigate.'], ['Can different teams use the same agent?', 'Only if they share the same appropriate knowledge and rules. Separate audiences often benefit from separate agents.'], ['Can it answer policy exceptions?', 'It should explain the standard policy and route exception decisions to the authorized owner.']],
    related: ['ai-sop-assistant', 'ai-onboarding-assistant', 'ai-help-desk'], keywords: ['AI operations manual', 'operations AI', 'AI process assistant'],
  }),
  'ai-onboarding-assistant': solution({
    slug: 'ai-onboarding-assistant', cluster: 'operations', title: 'AI Onboarding Assistant for the First Weeks',
    description: 'Help new employees find approved setup steps, role context, terminology, and the right person to ask.',
    what: 'An onboarding AI assistant answers recurring informational questions from a maintained new-starter guide while preserving manager, HR, IT, and training responsibilities.', audience: 'Teams that want new starters to find routine information without guessing which document or person holds it.',
    benefits: [['Reduce first-week friction', 'Explain setup sequence, common tools, terms, and routine expectations.'], ['Make ownership obvious', 'Tell new starters who handles access, policy, training, payroll, and role questions.'], ['Learn where onboarding fails', 'Use knowledge gaps to improve the source material for the next starter.']],
    steps: [['Define the onboarding audience', 'Separate universal company knowledge from role- or location-specific material.'], ['Build a time-based guide', 'Cover before day one, first day, first week, and first-month checkpoints.'], ['Protect private processes', 'Do not place personal records, passwords, or access credentials in the agent.']],
    question: 'What is my payroll account number?', answer: 'I do not have access to personal payroll records. The onboarding guide directs private payroll questions to HR through the secure employee channel.',
    faqs: [['Can it provision accounts?', 'Qlynk explains approved setup steps; it does not claim account provisioning or system access.'], ['Can it answer HR questions?', 'It can share general approved policy, while personal or interpretive questions should go to HR.'], ['How often should it be reviewed?', 'Review it whenever tools, policies, team ownership, office details, or onboarding steps change.']],
    related: ['ai-employee-training', 'ai-operations-manual', 'ai-help-desk'], keywords: ['AI onboarding assistant', 'employee onboarding AI', 'new hire AI assistant'],
  }),
  'ai-help-desk': solution({
    slug: 'ai-help-desk', cluster: 'operations', title: 'AI Help Desk for Internal How-To Questions',
    description: 'Answer routine internal questions from approved guidance and send access, incident, and account work to the proper channel.',
    what: 'A Qlynk help-desk agent is a self-service knowledge guide for common internal steps and troubleshooting, not a transactional IT service-management system.', audience: 'Small organizations with repeat how-to questions and a maintained internal knowledge set appropriate for the agent’s audience.',
    benefits: [['Deflect simple how-to questions', 'Explain common setup, access-request, and troubleshooting procedures.'], ['Make escalation precise', 'Tell employees when to stop and which approved channel or owner to contact.'], ['Improve the knowledge base', 'Track questions whose answers are missing, unclear, or outdated.']],
    steps: [['Choose low-risk topics', 'Start with routine how-to guidance that does not expose credentials or private system details.'], ['Write checks and stop points', 'Explain what to verify and when an incident or admin action is required.'], ['Keep contacts current', 'Review team ownership, request forms, hours, and emergency paths.']],
    question: 'Can you reset my password?', answer: 'I cannot access accounts or reset credentials. I can show you the approved self-service reset steps and the secure IT contact if those steps fail.',
    faqs: [['Does it replace ticketing software?', 'No. It provides knowledge and routing; account actions and ticket workflows need the appropriate system.'], ['Can we put passwords in it?', 'No. Never add passwords, access codes, secret keys, or private credentials.'], ['Can it serve customers too?', 'Use a clearly separate audience and knowledge set for public customer support.']],
    related: ['ai-customer-support', 'ai-operations-manual', 'ai-onboarding-assistant'], keywords: ['AI help desk', 'internal help desk AI', 'IT knowledge assistant'],
  }),

  'ai-property-assistant': solution({
    slug: 'ai-property-assistant', cluster: 'places', title: 'AI Property Assistant for Guests and Residents',
    description: 'Give people a focused guide to a property’s approved amenities, routines, rules, and support contacts.',
    what: 'A property AI assistant answers non-sensitive questions about a specific property and hands off access, emergencies, disputes, and changing availability.', audience: 'Property hosts, managers, residential teams, and facilities that repeatedly explain how a place works.',
    benefits: [['Answer place-specific questions', 'Explain arrival guidance, amenities, rules, equipment, local tips, and routine contacts.'], ['Protect sensitive access', 'Keep door codes, personal details, live occupancy, and private records out of a public agent.'], ['Update without reprinting', 'Revise the knowledge when property guidance or local recommendations change.']],
    steps: [['Choose the audience and access level', 'Separate public visitor information from guest- or resident-only guidance.'], ['Build the property guide', 'Add reviewed facts, FAQs, house rules, equipment notes, links, and emergency contacts.'], ['Test sensitive requests', 'Confirm the agent never exposes access codes or treats an emergency as routine chat.']],
    question: 'What is the front-door code?', answer: 'I cannot provide access credentials. Please use the secure arrival message or contact the property team through the verified channel.',
    faqs: [['Can I add check-in instructions?', 'Yes, but keep credentials and private booking details in a secure channel.'], ['Can it handle maintenance emergencies?', 'It can display the approved emergency route, but visitors should use the official urgent contact rather than wait in chat.'], ['Can I share it with a QR code?', 'You can share the public Qlynk link anywhere, including a QR code you create for the intended location.']],
    related: ['ai-real-estate-assistant', 'ai-hotel-concierge', 'ai-visitor-guide'], keywords: ['AI property assistant', 'property guide AI', 'AI for property management'],
  }),
  'ai-real-estate-assistant': solution({
    slug: 'ai-real-estate-assistant', cluster: 'places', title: 'AI Real Estate Assistant for Property Information',
    description: 'Help buyers, renters, and visitors explore approved listing facts, features, neighborhood context, and viewing steps.',
    what: 'A real-estate AI assistant is a conversational listing and inquiry guide. It explains substantiated property information and routes availability, offers, legal questions, and advice to licensed or authorized people.', audience: 'Agents, brokers, developers, and property teams with repeat questions about a listing or development.',
    benefits: [['Make the listing conversational', 'Answer questions about approved specifications, amenities, location context, and viewing logistics.'], ['Keep claims factual', 'Use the current listing record and avoid assumptions about condition, investment value, or future outcomes.'], ['Handoff commercial decisions', 'Route availability confirmation, negotiation, financing, and legal interpretation.']],
    steps: [['Verify the listing facts', 'Use approved measurements, features, disclosures, media, and current links.'], ['Set regulated boundaries', 'Define what requires a licensed professional or direct confirmation.'], ['Review whenever status changes', 'Update availability, pricing context, viewing information, and published documents promptly.']],
    question: 'Is this guaranteed to increase in value?', answer: 'I cannot predict or guarantee investment performance. I can explain the approved property facts and connect you with the agent for market context.',
    faqs: [['Can it give financial or legal advice?', 'No. It should provide approved property information and route advice to an appropriately qualified person.'], ['Can it confirm current availability?', 'Only if the maintained source is current; otherwise it should ask the visitor to confirm with the listing team.'], ['Can it cover an entire portfolio?', 'A narrowly scoped listing or development guide is usually clearer and easier to keep current.']],
    related: ['ai-property-assistant', 'ai-visitor-guide', 'ai-sales-assistant'], keywords: ['AI real estate assistant', 'real estate chatbot', 'property listing AI'],
  }),
  'ai-hotel-concierge': solution({
    slug: 'ai-hotel-concierge', cluster: 'places', title: 'AI Hotel Concierge for Routine Guest Questions',
    description: 'Answer approved questions about amenities, schedules, directions, policies, and local recommendations while keeping service actions human.',
    what: 'An AI hotel concierge is a guest information guide available through a link or widget. It explains property knowledge but does not claim access to reservations, rooms, payments, or live service systems.', audience: 'Hotels, guesthouses, resorts, and short-stay properties with frequent informational questions.',
    benefits: [['Support guests before arrival', 'Explain location, check-in windows, amenities, packing guidance, and transport options.'], ['Help during the stay', 'Make approved facility instructions, schedules, and local suggestions easy to ask.'], ['Escalate service requests', 'Send room access, maintenance, safety, billing, and reservation changes to staff.']],
    steps: [['Map the guest journey', 'Cover before arrival, check-in, stay, check-out, and post-stay questions.'], ['Separate static and live information', 'Label what the agent can explain and what staff must confirm.'], ['Publish at useful touchpoints', 'Add the link to pre-arrival messages, the website, room materials, or a QR code.']],
    question: 'Can you move my reservation to tomorrow?', answer: 'I cannot access or change reservations. Please contact the front desk or reservations team through the official number.',
    faqs: [['Can it book rooms or services?', 'Not by default. Qlynk provides knowledge and a human handoff; do not imply transactional integrations that are not implemented.'], ['Can it recommend local places?', 'Yes, from an approved and maintained list, with a note that hours and availability may change.'], ['Can we include emergency information?', 'Yes, clearly and prominently, while directing guests to official emergency and property contacts.']],
    related: ['ai-property-assistant', 'ai-visitor-guide', 'ai-campus-guide'], keywords: ['AI hotel concierge', 'hotel chatbot', 'guest AI assistant'],
  }),
  'ai-visitor-guide': solution({
    slug: 'ai-visitor-guide', cluster: 'places', title: 'AI Visitor Guide for Places and Events',
    description: 'Help visitors understand what to see, how to prepare, where to go, and whom to contact from one maintained guide.',
    what: 'An AI visitor guide is a conversational companion to approved place, venue, or event information, designed for orientation rather than live operational control.', audience: 'Venues, attractions, events, public spaces, campuses, and community organizations.',
    benefits: [['Answer planning questions', 'Explain hours, access, facilities, directions, expectations, and available experiences.'], ['Support on-site orientation', 'Help visitors locate areas and understand approved rules or context.'], ['Keep changing details qualified', 'Direct visitors to confirm live closures, tickets, schedules, or accessibility arrangements.']],
    steps: [['Define the visit stages', 'Organize information for planning, arrival, navigation, experience, and departure.'], ['Use inclusive source content', 'Add reviewed accessibility, family, language, and assistance information.'], ['Test time-sensitive questions', 'Make sure the agent distinguishes maintained guidance from details requiring live confirmation.']],
    question: 'Is the north entrance open right now?', answer: 'The visitor guide lists the north entrance during regular hours, but I do not have live closure data. Please check the venue alert page or contact staff.',
    faqs: [['Can it provide live opening information?', 'Only if you maintain that information as current. Otherwise it should link to or recommend an official live source.'], ['Can it support accessibility questions?', 'Yes, using precise approved information and a direct contact for individual arrangements.'], ['Where can visitors open it?', 'Use the Qlynk link on the website, tickets, email, signage, or QR codes.']],
    related: ['ai-museum-guide', 'ai-campus-guide', 'ai-hotel-concierge'], keywords: ['AI visitor guide', 'visitor assistant AI', 'venue AI guide'],
  }),
  'ai-museum-guide': solution({
    slug: 'ai-museum-guide', cluster: 'places', title: 'AI Museum Guide Built From Curatorial Knowledge',
    description: 'Let visitors explore approved object, exhibition, artist, and visitor information in their own words.',
    what: 'An AI museum guide is a conversational interpretation layer over reviewed curatorial and visitor content, with clear distinction between documented facts and open interpretation.', audience: 'Museums, galleries, archives, cultural sites, and exhibitions with maintained interpretive material.',
    benefits: [['Invite deeper questions', 'Connect objects, themes, people, periods, and approved resources conversationally.'], ['Keep provenance clear', 'Base factual claims on reviewed catalog and curatorial information.'], ['Support the visit', 'Explain facilities, access, programs, and where to find human assistance.']],
    steps: [['Choose the interpretive scope', 'Start with one collection, exhibition, route, or visitor audience.'], ['Prepare source context', 'Use readable labels, catalog records, approved essays, glossary terms, and visitor guidance.'], ['Test ambiguity', 'Check that disputed, uncertain, or interpretive topics are described with appropriate qualification.']],
    question: 'Is this definitely what the artist intended?', answer: 'The curatorial note documents one interpretation, but the artist’s definitive intention is not established in the approved source. I can explain the evidence and other published context.',
    faqs: [['Can it identify objects from a camera?', 'Do not assume image-recognition features. Build the guide around the approved objects and prompts you publish.'], ['Can it replace a human guide?', 'It offers another way to explore information; educators and guides provide context, dialogue, and judgment an agent should not claim.'], ['Can it cover visitor logistics too?', 'Yes, if the operational information is maintained and appropriate for the same audience.']],
    related: ['ai-visitor-guide', 'ai-campus-guide', 'knowledge-based-ai'], keywords: ['AI museum guide', 'museum chatbot', 'AI cultural guide'],
  }),
  'ai-campus-guide': solution({
    slug: 'ai-campus-guide', cluster: 'places', title: 'AI Campus Guide for Orientation and Information',
    description: 'Help students, staff, and visitors find approved campus information while routing personal records and urgent issues correctly.',
    what: 'An AI campus guide answers general questions about facilities, services, events, procedures, and orientation from knowledge selected for a defined campus audience.', audience: 'Schools, colleges, universities, training centers, business campuses, and multi-building organizations.',
    benefits: [['Improve orientation', 'Explain locations, services, terminology, schedules, and common procedures.'], ['Separate public from private', 'Keep student, employee, access, and case records out of a general knowledge agent.'], ['Route responsibility', 'Direct academic, administrative, safety, accessibility, and facilities needs to the official owner.']],
    steps: [['Choose one audience', 'Build for prospective students, current students, staff, or public visitors rather than mixing permissions.'], ['Add the current campus guide', 'Use official locations, services, policies, transport, contacts, and access information.'], ['Test urgent and personal questions', 'Confirm the agent redirects emergencies and refuses to expose or infer individual records.']],
    question: 'Can you tell me my exam result?', answer: 'I cannot access personal student records. Please use the secure student portal or contact the registrar through the official channel.',
    faqs: [['Can it access student systems?', 'Not by default. Qlynk is a knowledge guide and should not imply access to personal records.'], ['Can it give directions?', 'It can explain approved location and route information you add, while temporary closures should use a live official source.'], ['Can different campus groups use it?', 'Create a clearly defined audience and knowledge scope; separate agents may be safer for different permissions.']],
    related: ['ai-visitor-guide', 'ai-onboarding-assistant', 'ai-help-desk'], keywords: ['AI campus guide', 'campus chatbot', 'student information AI'],
  }),
};

export const solutionEntries = Object.values(solutionPages);

export function getSolutionsByCluster(cluster) {
  return solutionEntries.filter((page) => page.cluster === cluster);
}
