-- Introduce versioned agent types and service-managed owner rules without
-- exposing the immutable Qlynk platform prompt to browsers.

ALTER TABLE public.agent_configs
  ADD COLUMN IF NOT EXISTS agent_type TEXT NOT NULL DEFAULT 'personal';

ALTER TABLE public.agent_configs
  DROP CONSTRAINT IF EXISTS agent_configs_agent_type_check;

ALTER TABLE public.agent_configs
  ADD CONSTRAINT agent_configs_agent_type_check
  CHECK (agent_type IN (
    'personal',
    'business',
    'property',
    'operations',
    'product',
    'support',
    'custom'
  ));

COMMENT ON COLUMN public.agent_configs.agent_type IS
  'Approved behavior template. Existing agents remain personal by default.';

CREATE TABLE IF NOT EXISTS public.agent_rule_configs (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL,
  audience TEXT NOT NULL DEFAULT '',
  allowed_topics JSONB NOT NULL DEFAULT '[]'::jsonb,
  blocked_topics JSONB NOT NULL DEFAULT '[]'::jsonb,
  behavior_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  forbidden_behaviors JSONB NOT NULL DEFAULT '[]'::jsonb,
  uncertainty_message TEXT NOT NULL,
  escalation_message TEXT NOT NULL DEFAULT '',
  custom_instructions TEXT NOT NULL DEFAULT '',
  response_length TEXT NOT NULL DEFAULT 'balanced',
  scope_mode TEXT NOT NULL DEFAULT 'standard',
  daily_message_limit INTEGER,
  prompt_version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_rule_configs_purpose_length CHECK (char_length(purpose) BETWEEN 1 AND 500),
  CONSTRAINT agent_rule_configs_audience_length CHECK (char_length(audience) <= 300),
  CONSTRAINT agent_rule_configs_allowed_topics_array CHECK (
    jsonb_typeof(allowed_topics) = 'array' AND jsonb_array_length(allowed_topics) <= 20
  ),
  CONSTRAINT agent_rule_configs_blocked_topics_array CHECK (
    jsonb_typeof(blocked_topics) = 'array' AND jsonb_array_length(blocked_topics) <= 20
  ),
  CONSTRAINT agent_rule_configs_behavior_rules_array CHECK (
    jsonb_typeof(behavior_rules) = 'array' AND jsonb_array_length(behavior_rules) <= 20
  ),
  CONSTRAINT agent_rule_configs_forbidden_behaviors_array CHECK (
    jsonb_typeof(forbidden_behaviors) = 'array' AND jsonb_array_length(forbidden_behaviors) <= 20
  ),
  CONSTRAINT agent_rule_configs_uncertainty_length CHECK (char_length(uncertainty_message) BETWEEN 1 AND 500),
  CONSTRAINT agent_rule_configs_escalation_length CHECK (char_length(escalation_message) <= 500),
  CONSTRAINT agent_rule_configs_custom_instructions_length CHECK (char_length(custom_instructions) <= 2000),
  CONSTRAINT agent_rule_configs_response_length_check CHECK (response_length IN ('concise', 'balanced', 'detailed')),
  CONSTRAINT agent_rule_configs_scope_mode_check CHECK (scope_mode IN ('standard', 'strict')),
  CONSTRAINT agent_rule_configs_daily_limit_check CHECK (
    daily_message_limit IS NULL OR daily_message_limit BETWEEN 10 AND 10000
  ),
  CONSTRAINT agent_rule_configs_prompt_version_check CHECK (prompt_version BETWEEN 1 AND 1000)
);

ALTER TABLE public.agent_rule_configs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.agent_rule_configs FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.agent_rule_configs TO service_role;

COMMENT ON TABLE public.agent_rule_configs IS
  'Private, validated owner behavior rules. Accessible only through authenticated server APIs.';

CREATE TABLE IF NOT EXISTS public.agent_rule_config_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  agent_type TEXT NOT NULL,
  rules JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_rule_config_versions_unique UNIQUE (user_id, version),
  CONSTRAINT agent_rule_config_versions_agent_type_check CHECK (agent_type IN (
    'personal', 'business', 'property', 'operations', 'product', 'support', 'custom'
  )),
  CONSTRAINT agent_rule_config_versions_rules_object CHECK (jsonb_typeof(rules) = 'object')
);

ALTER TABLE public.agent_rule_config_versions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.agent_rule_config_versions FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.agent_rule_config_versions TO service_role;

CREATE TABLE IF NOT EXISTS public.agent_security_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  visitor_key_hash TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT agent_security_events_type_check CHECK (event_type IN ('prompt_injection', 'off_topic', 'safety')),
  CONSTRAINT agent_security_events_hash_length CHECK (char_length(visitor_key_hash) = 64),
  CONSTRAINT agent_security_events_metadata_object CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS agent_security_events_owner_created_idx
ON public.agent_security_events (agent_owner_id, created_at DESC);

ALTER TABLE public.agent_security_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.agent_security_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.agent_security_events TO service_role;

COMMENT ON TABLE public.agent_security_events IS
  'Privacy-minimized scope and safety events. Raw visitor prompts are intentionally not stored here.';

CREATE OR REPLACE FUNCTION public.save_agent_rule_config(
  p_owner_id UUID,
  p_agent_type TEXT,
  p_rules JSONB
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  next_version INTEGER;
BEGIN
  IF p_owner_id IS NULL OR p_rules IS NULL OR jsonb_typeof(p_rules) <> 'object' THEN
    RAISE EXCEPTION 'Invalid agent rule configuration';
  END IF;

  -- Serialize prompt-version allocation per owner, including the first save.
  -- Locking the durable auth row avoids duplicate version numbers from two
  -- dashboard tabs saving at the same time.
  PERFORM 1
  FROM auth.users
  WHERE id = p_owner_id
  FOR UPDATE;

  SELECT COALESCE(prompt_version, 0) + 1
  INTO next_version
  FROM public.agent_rule_configs
  WHERE user_id = p_owner_id;

  next_version := COALESCE(next_version, 1);

  INSERT INTO public.agent_rule_configs (
    user_id,
    purpose,
    audience,
    allowed_topics,
    blocked_topics,
    behavior_rules,
    forbidden_behaviors,
    uncertainty_message,
    escalation_message,
    custom_instructions,
    response_length,
    scope_mode,
    daily_message_limit,
    prompt_version,
    updated_at
  ) VALUES (
    p_owner_id,
    p_rules->>'purpose',
    COALESCE(p_rules->>'audience', ''),
    COALESCE(p_rules->'allowed_topics', '[]'::jsonb),
    COALESCE(p_rules->'blocked_topics', '[]'::jsonb),
    COALESCE(p_rules->'behavior_rules', '[]'::jsonb),
    COALESCE(p_rules->'forbidden_behaviors', '[]'::jsonb),
    p_rules->>'uncertainty_message',
    COALESCE(p_rules->>'escalation_message', ''),
    COALESCE(p_rules->>'custom_instructions', ''),
    COALESCE(p_rules->>'response_length', 'balanced'),
    COALESCE(p_rules->>'scope_mode', 'standard'),
    NULLIF(p_rules->>'daily_message_limit', '')::INTEGER,
    next_version,
    now()
  )
  ON CONFLICT (user_id) DO UPDATE SET
    purpose = EXCLUDED.purpose,
    audience = EXCLUDED.audience,
    allowed_topics = EXCLUDED.allowed_topics,
    blocked_topics = EXCLUDED.blocked_topics,
    behavior_rules = EXCLUDED.behavior_rules,
    forbidden_behaviors = EXCLUDED.forbidden_behaviors,
    uncertainty_message = EXCLUDED.uncertainty_message,
    escalation_message = EXCLUDED.escalation_message,
    custom_instructions = EXCLUDED.custom_instructions,
    response_length = EXCLUDED.response_length,
    scope_mode = EXCLUDED.scope_mode,
    daily_message_limit = EXCLUDED.daily_message_limit,
    prompt_version = next_version,
    updated_at = now();

  INSERT INTO public.agent_rule_config_versions (user_id, version, agent_type, rules)
  VALUES (p_owner_id, next_version, p_agent_type, p_rules);

  INSERT INTO public.agent_configs (user_id, agent_type, updated_at)
  VALUES (p_owner_id, p_agent_type, now())
  ON CONFLICT (user_id) DO UPDATE SET
    agent_type = EXCLUDED.agent_type,
    updated_at = now();

  RETURN next_version;
END;
$$;

REVOKE ALL ON FUNCTION public.save_agent_rule_config(UUID, TEXT, JSONB)
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.save_agent_rule_config(UUID, TEXT, JSONB)
TO service_role;

CREATE OR REPLACE VIEW public.agent_configs_public
WITH (security_barrier = true)
AS
SELECT
  id,
  user_id,
  agent_name,
  bio,
  agent_avatar,
  welcome_message,
  is_enabled,
  primary_color,
  position,
  access_level,
  chat_bg_color,
  user_bubble_color,
  ai_bubble_color,
  cta_button_color,
  cta_text_color,
  pre_chat_text_color,
  gatekeeper_text_color,
  font_family,
  profession,
  social_links,
  agent_type
FROM public.agent_configs;

REVOKE ALL ON TABLE public.agent_configs_public FROM PUBLIC;
GRANT SELECT ON TABLE public.agent_configs_public TO anon, authenticated;

-- Replace the historical message trigger so usage is reserved atomically by
-- the server before an AI request rather than incremented after a race-prone
-- read/check sequence.
CREATE OR REPLACE FUNCTION public.update_conversation_message_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.agent_conversations
    SET message_count = COALESCE(message_count, 0) + 1,
        updated_at = now()
    WHERE id = NEW.conversation_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.agent_conversations
    SET message_count = (
          SELECT count(*)
          FROM public.agent_messages
          WHERE conversation_id = OLD.conversation_id
        ),
        updated_at = now()
    WHERE id = OLD.conversation_id;
  END IF;
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.consume_agent_message_credit(
  p_owner_id UUID,
  p_message_limit INTEGER
)
RETURNS TABLE(allowed BOOLEAN, messages_used INTEGER, remaining INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  updated_count INTEGER;
  current_count INTEGER;
BEGIN
  IF p_owner_id IS NULL OR p_message_limit IS NULL OR p_message_limit <= 0 THEN
    RAISE EXCEPTION 'Invalid message credit parameters';
  END IF;

  UPDATE public.subscriptions
  SET messages_used = COALESCE(subscriptions.messages_used, 0) + 1
  WHERE user_id = p_owner_id
    AND COALESCE(subscriptions.messages_used, 0) < p_message_limit
  RETURNING subscriptions.messages_used INTO updated_count;

  IF updated_count IS NOT NULL THEN
    RETURN QUERY SELECT TRUE, updated_count, GREATEST(p_message_limit - updated_count, 0);
    RETURN;
  END IF;

  SELECT COALESCE(subscriptions.messages_used, 0)
  INTO current_count
  FROM public.subscriptions
  WHERE user_id = p_owner_id;

  RETURN QUERY SELECT FALSE, COALESCE(current_count, p_message_limit), 0;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_agent_message_credit(UUID, INTEGER)
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_agent_message_credit(UUID, INTEGER)
TO service_role;
